name    'erwbgy-ntp'
version '0.7.0'
source 'git.com:erwbgy/puppet-ntp.git'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'configure and manage ntpd'
description 'Configure and manage the NTP daemon on a Linux hosts'
project_page 'https://github.com/erwbgy/puppet-ntp'
